# Generated by Django 3.2.12 on 2022-08-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galaxy_group', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
