# Generated by Django 3.2.12 on 2022-08-14 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_found', models.IntegerField()),
                ('species_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pigeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('MALE', 'Laki Laki'), ('FEMALE', 'Perempuan')], max_length=20, null=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app15listfieldsample.bird')),
            ],
        ),
    ]
