# Generated by Django 3.2.12 on 2022-07-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app8singleroute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburator',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app8singleroute.car'),
        ),
    ]
