# Generated by Django 3.2.12 on 2022-08-17 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_address', models.CharField(max_length=128, unique=True)),
                ('host_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('current_certificate_uuid', models.UUIDField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('property_type', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=256)),
                ('amenities', models.JSONField()),
                ('total_bedrooms', models.PositiveSmallIntegerField()),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('max_guests', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
            },
        ),
    ]
