# Generated by Django 3.2.12 on 2022-07-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(max_length=100)),
                ('dimension', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
    ]
